# Generated by Django 4.0.5 on 2022-06-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='썸네일')),
                ('explanation', models.CharField(max_length=256, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('effective_data', models.DateTimeField()),
                ('expiration_data', models.DateTimeField()),
                ('active', models.BooleanField()),
            ],
        ),
    ]
