# Generated by Django 4.0.5 on 2022-06-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='effective_data',
            new_name='effective_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='expiration_data',
            new_name='expiration_date',
        ),
    ]
