# Generated by Django 4.0.5 on 2022-06-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_interest_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(verbose_name='비밀번호'),
        ),
    ]
